FROM openjdk:17
WORKDIR /app

# 환경 변수 설정 (Docker Build 시점에 전달 가능)
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_URL
ARG JWT_SECRET
ARG CLOVA_OCR_URL
ARG CLOVA_SECRET_KEY
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG S3_BUCKET_NAME

# 환경 변수 값을 Docker 컨테이너 실행 시에도 사용할 수 있도록 설정
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_URL=${DB_URL}
ENV JWT_SECRET=${JWT_SECRET}
ENV CLOVA_OCR_URL=${CLOVA_OCR_URL}
ENV CLOVA_SECRET_KEY=${CLOVA_SECRET_KEY}
ENV S3_ACCESS_KEY=${S3_ACCESS_KEY}
ENV S3_SECRET_KEY=${S3_SECRET_KEY}
ENV S3_BUCKET_NAME=${S3_BUCKET_NAME}

COPY build/libs/*.jar app.jar
CMD ["java", "-jar", "app.jar"]
