spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        default_schema: ${DB_USERNAME}
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secret: ${JWT_SECRET}

  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000
    mail_auth_code_expiration: 600000 # 10분

clova:
  ocr:
    url: ${CLOVA_OCR_URL}
    secret-key: ${CLOVA_SECRET_KEY}
    template-ids:
      - 36405

springdoc:
  show-login-endpoint: true

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack:
      auto: false

codef:
  public:
    key: ${PUBLIC_KEY}
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  valid:
    url: ${VALID_URL}
