package Seoul_Milk.sm_server.mock.repository;

import Seoul_Milk.sm_server.domain.member.entity.MemberEntity;
import Seoul_Milk.sm_server.domain.member.repository.MemberRepository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMemberRepository implements MemberRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MemberEntity> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Optional<MemberEntity> findById(Long id) {
        return Optional.empty();
    }

    @Override
    public MemberEntity getById(Long id) {
        return null;
    }

    @Override
    public Optional<MemberEntity> findByEmployeeId(String employeeId) {
        return Optional.empty();
    }

    @Override
    public MemberEntity getByEmployeeId(String employeeId) {
        return null;
    }

    @Override
    public Optional<MemberEntity> findByEmail(String email) {
        return Optional.empty();
    }

    @Override
    public Boolean existsByEmployeeId(String employeeId) {
        return null;
    }

    @Override
    public MemberEntity save(MemberEntity memberEntity) {
        return null;
    }
}
